name: Deploy to S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.19"

      - name: Install dependencies
        run: npm install
        working-directory: ./funntail_website

      - name: Build project
        run: npm run build
        working-directory: ./funntail_website

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1

      - name: Sync S3 bucket
        run: aws s3 sync dist s3://funntail-bucket --delete --region eu-west-2
        working-directory: ./funntail_website

      - name: CloudFront Invalidation
        run: aws cloudfront create-invalidation --distribution-id E2YRBHJE7WASUV --paths "/*"

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-west-2
